<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../MonitorDeviceState.cs" Link="MonitorDeviceState.cs" />
    <Compile Include="../TrayIconIdentity.cs" Link="TrayIconIdentity.cs" />
    <Compile Include="../TrayIconRegistration.cs" Link="TrayIconRegistration.cs" />
  </ItemGroup>
</Project>
